export default [
	{
		id: 'basilica-san-francesco',
		oliassiTitleno: 'Assisal Olive Notes — Basilica di San Francesco d’Assisi',
		coords: { lat: 43.0705, lng: 12.6175 },
		notaolDescrip: "This is the heart of Assisi, a two-story basilica dedicated to Saint Francis. Its lower church houses his tomb, while the upper one shines with Giotto’s frescoes. Every stone speaks of humility and faith, and the view from the terrace opens up to the Umbrian valley. In the mornings, you can hear the soft jingle of bells and the smell of fresh bread from the nearest bakery.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/BasilicaFrancesco.png'),
	},
	{
		id: 'rocca-maggiore',
		oliassiTitleno: 'Assisal Olive Notes — Rocca Maggiore',
		coords: { lat: 43.0748, lng: 12.6154 },
		notaolDescrip: "A medieval fortress that has guarded the city since the 12th century. From here, you can enjoy a panorama of Assisi’s tiled roofs and green hills. Inside, you’ll find historic halls, observation towers, and a wind reminiscent of old battles.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/RoccaMaggiore.png'),
	},
	{
		id: 'piazza-del-comune',
		oliassiTitleno: 'Assisal Olive Notes — Piazza del Comune',
		coords: { lat: 43.0712, lng: 12.6167 },
		notaolDescrip: "The central square of the city, where the Roman columns of the Temple of Minerva harmoniously coexist with medieval facades. It is worth drinking coffee here and listening to the locals discuss the news to the quiet sound of the fountain.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/PiazzaComune.png'),
	},
	{
		id: 'temple-of-minerva',
		oliassiTitleno: 'Assisal Olive Notes — Temple of Minerva',
		coords: { lat: 43.0713, lng: 12.6167 },
		notaolDescrip: "Ancient temple of the 1st century BC is a symbol of the immutability of time. The columns, which have been standing for two thousand years, seem to be gates between eras. Inside is now the church of St. Mary of Minerva.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/TempleMinerva.png'),
	},
	{
		id: 'basilica-santa-chiara',
		oliassiTitleno: 'Assisal Olive Notes — Basilica di Santa Chiara',
		coords: { lat: 43.0718, lng: 12.6185 },
		notaolDescrip: "The church of St. Clare, a disciple of Francis. Its pink stone shines in the sun, and the terrace offers a view of the valley. Inside is a silence that makes you forget about everything earthly.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/SantaChiara.png'),
	},
	{
		id: 'eremo-delle-carceri',
		oliassiTitleno: 'Assisal Olive Notes — Eremo delle Carceri',
		coords: { lat: 43.0783, lng: 12.6424 },
		notaolDescrip: "A gorge in the Subasio mountains where Francis sought peace and prayer. The silence, birdsong and the scent of pine trees make it feel as if time has stood still.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/EremoCarceri.png'),
	},
	{
		id: 'porta-san-giacomo',
		oliassiTitleno: 'Assisal Olive Notes — Porta San Giacomo',
		coords: { lat: 43.0732, lng: 12.6199 },
		notaolDescrip: "An old city gate with a panorama that is especially beautiful at sunset. Pilgrims once passed through here, but today tourists stop to take photos against the pink sky.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/PortaGiacomo.png'),
	},
	{
		id: 'via-san-francesco',
		oliassiTitleno: 'Assisal Olive Notes — Via San Francesco',
		coords: { lat: 43.0710, lng: 12.6171 },
		notaolDescrip: "The main street leading to the basilica. It is paved with stone and on both sides are small shops selling olive oil, wine and ceramics.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/ViaFrancesco.png'),
	},
	{
		id: 'cathedral-san-rufino',
		oliassiTitleno: 'Assisal Olive Notes — Cathedral of San Rufino',
		coords: { lat: 43.0717, lng: 12.6201 },
		notaolDescrip: "A cathedral with a Romanesque facade from the 12th century. Francis and Clare were baptized here. Inside, soft light reigns, falling through colored stained glass windows.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/SanRufino.png'),
	},
	{
		id: 'monte-subasio',
		oliassiTitleno: 'Assisal Olive Notes — Monte Subasio Natural Park',
		coords: { lat: 43.0672, lng: 12.6689 },
		notaolDescrip: "Mount Subasio is a legendary neighborhood of Assisi, where the forests smell of rosemary. From the top, you can see Trentino and Perugia. It is a place for hiking and inspiration.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/MonteSubasio.png'),
	},
	{
		id: 'basilica-santa-maria-angeli',
		oliassiTitleno: 'Assisal Olive Notes — Basilica di Santa Maria degli Angeli',
		coords: { lat: 43.0604, lng: 12.5859 },
		notaolDescrip: "A majestic basilica at the bottom of the valley that preserves a small chapel - the Portiuncula, where the Franciscan Order was born.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/SantaMaria.png'),
	},
	{
		id: 'fontana-tre-leoni',
		oliassiTitleno: 'Assisal Olive Notes — Fontana dei Tre Leoni',
		coords: { lat: 43.0711, lng: 12.6164 },
		notaolDescrip: "The fountain with the three lions is a symbol of the city's power. In the evening, its water sparkles in the light of lanterns, and music from nearby cafes sounds.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/TreLeoni.png'),
	},
	{
		id: 'oratorio-pellegrini',
		oliassiTitleno: 'Assisal Olive Notes — Oratorio dei Pellegrini',
		coords: { lat: 43.0708, lng: 12.6178 },
		notaolDescrip: "A former 15th-century pilgrim shelter with frescoes showing the path of faith. Today, it is a museum and a quiet gallery with the aroma of old wood.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/OratorioPellegrini.png'),
	},
	{
		id: 'museo-porziuncola',
		oliassiTitleno: 'Assisal Olive Notes — Museo della Porziuncola',
		coords: { lat: 43.0603, lng: 12.5857 },
		notaolDescrip: "A museum at the Basilica of St. Mary, where documents, frescoes and relics telling the story of the Franciscans are collected.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/MuseoPorzziuncola.png'),
	},
	{
		id: 'belvedere-assisi',
		oliassiTitleno: 'Assisal Olive Notes — Belvedere di Assisi',
		coords: { lat: 43.0745, lng: 12.6221 },
		notaolDescrip: "The best vantage point for sunrises. Here, the city dissolves in golden light and the bells awaken the valley—a magical moment that is impossible to forget.",
		imageOfAssiLoat: require('../AssisalOliveNotesAssets/AssisalOliveNotesImages/imageOfAssiLoats/BelvedereAssisi.png'),
	},
]
