export default [
	{ id: 'st-francis-city', text: 'Assisi is the city of St. Francis, the founder of the Order of Friars Minor.' },
	{ id: 'basilica-unesco', text: 'Its basilica is a UNESCO World Heritage Site.' },
	{ id: 'pink-limestone', text: 'The city is built entirely of pink limestone.' },
	{ id: 'altitude', text: 'Assisi stands on the slopes of Mount Subasio at an altitude of over 400 meters.' },
	{ id: 'population', text: 'It has a population of only about 28,000.' },
	{ id: 'no-ac', text: 'Many buildings do not have air conditioning - the walls themselves keep it cool.' },
	{ id: 'narrow-streets', text: 'Assisi\'s narrow streets are ideal for walking.' },
	{ id: 'calendimaggio', text: 'Every year the Calendimaggio festival is held - a reenactment of medieval scenes.' },
	{ id: 'patron-of-animals', text: 'St. Francis is considered the patron saint of all animals.' },
	{ id: 'animal-blessing', text: 'On his day of remembrance, animals are blessed near the basilica.' },
	{ id: 'no-traffic-lights', text: 'There are no traffic lights in the city.' },
	{ id: 'best-time', text: 'The best time to visit is May and September.' },
	{ id: 'evening-lanterns', text: 'In the evening, Assisi shines with warm yellow lanterns.' },
	{ id: 'bread-olive-oil', text: 'Local bakers add olive oil to their bread.' },
	{ id: 'mount-subasio-volcano', text: 'Mount Subasio is a former volcano.' },
	{ id: 'microclimate', text: 'Assisi has its own microclimatic valley, warmer than neighboring cities.' },
	{ id: 'facade-law', text: 'The city has a law that prohibits changing old facades.' },
	{ id: 'filmed-50s', text: 'Assisi was filmed in films about Italy in the 50s.' },
	{ id: 'herb-scents', text: 'Every house smells of lavender or rosemary.' },
	{ id: 'small-sanctuaries', text: 'On every corner there are small sanctuaries with lamps.' },
	{ id: 'day-of-peace', text: 'It hosts the “Day of Peace” – an international event of interreligious dialogue.' },
	{ id: 'silence-sound', text: 'Locals say that the silence of Assisi “has a sound”.' },
	{ id: 'old-olive-oil', text: 'The oldest olive oil in the city has been produced by a monastery since the 13th century.' },
	{ id: 'dove-knockers', text: 'Many doors have ancient knockers in the shape of doves.' },
	{ id: 'roads-of-peace-map', text: 'Every tourist receives a map of the “Strade della Pace” – the roads of peace.' },
	{ id: 'coffee-porcelain', text: 'Coffee here is served only in porcelain cups.' },
	{ id: 'cool-wind', text: 'Even on the hottest day, a cool wind blows from the mountains.' },
	{ id: 'easter-branches', text: 'At Easter, the streets are decorated with green branches.' },
	{ id: 'children-stories', text: 'Local children know the stories of St. Francis better than textbooks.' },
	{ id: 'perfect-triangle', text: 'Assisi is the only city in Italy where the temple, mountain and valley form a perfect triangle on the map.' },
]